from .platforms.MobileScreen.mobile_screen import RidersMobileScreen
from .platforms.TabletScreen.tablet_screen import RidersTabletScreen
from .platforms.DesktopScreen.desktop_screen import RidersDesktopScreen
